// GET posts
const GET_QUESTIONS = 
{
    REQUEST: 'GET_QUESTIONS_REQUEST',
    RECEIVE: 'GET_QUESTIONS_RECEIVE',
    FAILURE: 'GET_QUESTIONS_FAILURE'
}

const GET_BLOG =
{
    REQUEST: 'GET_BLOG_REQUEST',
    RECEIVE: 'GET_BLOG_RECEIVE',
    FAILURE: 'GET_BLOG_FAILURE'
}

export {
    GET_QUESTIONS,
    GET_BLOG
}